services:
  app:
    build:
      context: .
    command: npm run dev
    ports:
      - "3020:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
